/**
 * Borsa İstanbul (BIST) Eksiksiz Tüm Hisseler ve Sektör Kataloğu (550+ Hisse)
 */

export interface BISTStock {
  ticker: string;
  name: string;
  sector: string;
}

export const ALL_BIST_STOCKS: BISTStock[] = [
  // A
  { ticker: "A1CAP", name: "A1 Capital Yatırım", sector: "Finansal Hizmetler" },
  { ticker: "ACSEL", name: "Acıselsan Acıpayam Selüloz", sector: "Kimya" },
  { ticker: "ADEL",  name: "Adel Kalemcilik", sector: "İmalat / Kırtasiye" },
  { ticker: "ADESE", name: "Adese Gayrimenkul", sector: "Gayrimenkul" },
  { ticker: "ADGYO", name: "Adra GYO", sector: "Gayrimenkul" },
  { ticker: "AEFES", name: "Anadolu Efes", sector: "Gıda & İçecek" },
  { ticker: "AFYON", name: "Afyon Çimento", sector: "Çimento & Yapı" },
  { ticker: "AGESA", name: "Agesa Hayat Emeklilik", sector: "Sigortacılık" },
  { ticker: "AGHOL", name: "Anadolu Grubu Holding", sector: "Holding" },
  { ticker: "AGROT", name: "Agrotech Teknoloji", sector: "Teknoloji" },
  { ticker: "AHGAZ", name: "Ahlatcı Doğalgaz", sector: "Enerji" },
  { ticker: "AKBNK", name: "Akbank", sector: "Bankacılık" },
  { ticker: "AKCNS", name: "Akçansa Çimento", sector: "Çimento & Yapı" },
  { ticker: "AKENR", name: "Akenerji Elektrik", sector: "Enerji" },
  { ticker: "AKFGY", name: "Akfen GYO", sector: "Gayrimenkul" },
  { ticker: "AKFYE", name: "Akfen Yenilenebilir Enerji", sector: "Enerji" },
  { ticker: "AKGRT", name: "Aksigorta", sector: "Sigortacılık" },
  { ticker: "AKMGY", name: "Akmerkez GYO", sector: "Gayrimenkul" },
  { ticker: "AKSA",  name: "Aksa Akrilik", sector: "Kimya" },
  { ticker: "AKSEN", name: "Aksa Enerji", sector: "Enerji" },
  { ticker: "AKSUE", name: "Aksu Enerji", sector: "Enerji" },
  { ticker: "AKYHO", name: "Akdeniz Yatırım Holding", sector: "Holding" },
  { ticker: "ALARK", name: "Alarko Holding", sector: "Holding" },
  { ticker: "ALBRK", name: "Albaraka Türk", sector: "Bankacılık" },
  { ticker: "ALCAR", name: "Alarko Carrier", sector: "İklimlendirme" },
  { ticker: "ALCTL", name: "Alcatel Lucent Teletaş", sector: "Telekomünikasyon" },
  { ticker: "ALFAS", name: "Alfa Solar Enerji", sector: "Enerji" },
  { ticker: "ALGYO", name: "Alarko GYO", sector: "Gayrimenkul" },
  { ticker: "ALKA",  name: "Alkim Kağıt", sector: "Kağıt & Ambalaj" },
  { ticker: "ALKIM", name: "Alkim Kimya", sector: "Kimya" },
  { ticker: "ALMAD", name: "Altınyağ Madencilik", sector: "Madencilik" },
  { ticker: "ALTNY", name: "Altınay Savunma", sector: "Savunma" },
  { ticker: "ANELE", name: "Anel Elektrik", sector: "Mühendislik & Enerji" },
  { ticker: "ANGEN", name: "Anatolia Tanı Biyoteknoloji", sector: "Sağlık & Biyoteknoloji" },
  { ticker: "ANHYT", name: "Anadolu Hayat Emeklilik", sector: "Sigortacılık" },
  { ticker: "ANSGR", name: "Anadolu Sigorta", sector: "Sigortacılık" },
  { ticker: "ARASE", name: "Doğu Aras Enerji", sector: "Enerji" },
  { ticker: "ARCLK", name: "Arçelik", sector: "Dayanıklı Tüketim" },
  { ticker: "ARDYZ", name: "Ardyz Bilişim", sector: "Teknoloji" },
  { ticker: "ARENA", name: "Arena Bilgisayar", sector: "Teknoloji" },
  { ticker: "ARSAN", name: "Arsan Tekstil", sector: "Tekstil" },
  { ticker: "ARTMS", name: "Artemis Halı", sector: "Tekstil / Ev Tekstili" },
  { ticker: "ARZUM", name: "Arzum Ev Aletleri", sector: "Dayanıklı Tüketim" },
  { ticker: "ASELS", name: "Aselsan", sector: "Savunma" },
  { ticker: "ASGYO", name: "Asce GYO", sector: "Gayrimenkul" },
  { ticker: "ASTOR", name: "Astor Enerji", sector: "Enerji" },
  { ticker: "ASUZU", name: "Anadolu Isuzu", sector: "Otomotiv" },
  { ticker: "ATAGY", name: "Ata GYO", sector: "Gayrimenkul" },
  { ticker: "ATAKP", name: "Atakey Patates", sector: "Gıda & Tarım" },
  { ticker: "ATATP", name: "ATP Bilgisayar", sector: "Teknoloji" },
  { ticker: "ATEKS", name: "Akın Tekstil", sector: "Tekstil" },
  { ticker: "AVGYO", name: "Avrasya GYO", sector: "Gayrimenkul" },
  { ticker: "AVHOL", name: "Avrupa Yatırım Holding", sector: "Holding" },
  { ticker: "AVOD",  name: "A.V.O.D. Kurutulmuş Gıda", sector: "Gıda" },
  { ticker: "AVPGY", name: "Avrupakent GYO", sector: "Gayrimenkul" },
  { ticker: "AVTUR", name: "Avrasya Petrol ve Turizm", sector: "Turizm" },
  { ticker: "AYCES", name: "Altın Yunus Çeşme", sector: "Turizm" },
  { ticker: "AYDEM", name: "Aydem Yenilenebilir Enerji", sector: "Enerji" },
  { ticker: "AYEN",  name: "Ayen Enerji", sector: "Enerji" },
  { ticker: "AYES",  name: "Ayes Çelik Hasır", sector: "Demir Çelik" },
  { ticker: "AYGAZ", name: "Aygaz", sector: "Enerji / Petrol" },
  { ticker: "AZTEK", name: "Aztek Teknoloji", sector: "Teknoloji" },

  // B
  { ticker: "BAGFS", name: "Bağfaş Gübre", sector: "Kimya & Tarım" },
  { ticker: "BAKAB", name: "Bak Ambalaj", sector: "Kağıt & Ambalaj" },
  { ticker: "BALAT", name: "Balatacılar Balatacılık", sector: "Otomotiv Yan Sanayi" },
  { ticker: "BANVT", name: "Banvit", sector: "Gıda" },
  { ticker: "BARMA", name: "Barem Ambalaj", sector: "Kağıt & Ambalaj" },
  { ticker: "BASGZ", name: "Başkent Doğalgaz", sector: "Enerji" },
  { ticker: "BAYRK", name: "Bayrak Ebt Taban", sector: "Ayakkabı / İmalat" },
  { ticker: "BEGYO", name: "Batı Ege GYO", sector: "Gayrimenkul" },
  { ticker: "BERA",  name: "Bera Holding", sector: "Holding" },
  { ticker: "BEYAZ", name: "Beyaz Filo Oto Kiralama", sector: "Otomotiv / Filo" },
  { ticker: "BFREN", name: "Bosch Fren Sistemleri", sector: "Otomotiv" },
  { ticker: "BIENY", name: "Bien Yapı Ürünleri", sector: "Seramik & Yapı" },
  { ticker: "BIGCH", name: "BigChefs Restoranları", sector: "Gıda & İçecek" },
  { ticker: "BIMAS", name: "BİM Birleşik Mağazalar", sector: "Perakende" },
  { ticker: "BINHO", name: "1000 Yatırımlar Holding", sector: "Holding / Ulaşım" },
  { ticker: "BIOEN", name: "Biotrend Çevre ve Enerji", sector: "Enerji" },
  { ticker: "BIZIM", name: "Bizim Toptan Satış", sector: "Perakende" },
  { ticker: "BJKAS", name: "Beşiktaş Futbol Yatırımları", sector: "Spor" },
  { ticker: "BLCYT", name: "Bilici Yatırım", sector: "Tekstil" },
  { ticker: "BMSCH", name: "BMS Çelik Hasır", sector: "Demir Çelik" },
  { ticker: "BMSTL", name: "BMS Birleşik Metal", sector: "Demir Çelik" },
  { ticker: "BNTAS", name: "Bantaş Ambalaj", sector: "Kağıt & Ambalaj" },
  { ticker: "BOBET", name: "Boğaziçi Beton", sector: "Çimento & Yapı" },
  { ticker: "BORLS", name: "Borlease Otomotiv", sector: "Otomotiv / Filo" },
  { ticker: "BORSK", name: "Bor Şeker", sector: "Gıda & Tarım" },
  { ticker: "BOSSA", name: "Bossa Ticaret ve Sanayi", sector: "Tekstil" },
  { ticker: "BRISA", name: "Brisa Lastik", sector: "Otomotiv" },
  { ticker: "BRKO",  name: "Birko Birleşik Koyunlular", sector: "Tekstil" },
  { ticker: "BRKSN", name: "Berkosan Yalıtım", sector: "Kimya / Yalıtım" },
  { ticker: "BRKVY", name: "Birikim Varlık Yönetim", sector: "Finansal Hizmetler" },
  { ticker: "BRLSM", name: "Birleşim Mühendislik", sector: "Mühendislik" },
  { ticker: "BRMEN", name: "Birlik Mensucat", sector: "Tekstil" },
  { ticker: "BRSAN", name: "Borusan Boru Sanayi", sector: "Demir Çelik" },
  { ticker: "BRYAT", name: "Borusan Yatırım", sector: "Holding" },
  { ticker: "BSOKE", name: "Batısöke Çimento", sector: "Çimento & Yapı" },
  { ticker: "BTCIM", name: "Batıçim Çimento", sector: "Çimento & Yapı" },
  { ticker: "BUCIM", name: "Bursa Çimento", sector: "Çimento & Yapı" },
  { ticker: "BURCE", name: "Burçelik Çelik Döküm", sector: "Demir Çelik" },
  { ticker: "BURVA", name: "Burçelik Vana", sector: "Makine" },
  { ticker: "BVSAN", name: "Bülbüloğlu Vinç", sector: "Makine" },
  { ticker: "BYDNR", name: "Baydöner Restoranları", sector: "Gıda & İçecek" },

  // C - Ç
  { ticker: "CANTE", name: "Çan2 Termik Enerji", sector: "Enerji" },
  { ticker: "CATES", name: "Çates Elektrik", sector: "Enerji" },
  { ticker: "CCOLA", name: "Coca-Cola İçecek", sector: "Gıda & İçecek" },
  { ticker: "CELHA", name: "Çelik Halat ve Tel", sector: "Demir Çelik" },
  { ticker: "CEMAS", name: "Çemaş Döküm", sector: "Döküm / Metal" },
  { ticker: "CEMTS", name: "Çemtaş Çelik", sector: "Demir Çelik" },
  { ticker: "CEMZY", name: "Cem Zeytin", sector: "Gıda" },
  { ticker: "CEOEM", name: "Ceo Event Medya", sector: "Medya / Etkinlik" },
  { ticker: "CIMSA", name: "Çimsa Çimento", sector: "Çimento & Yapı" },
  { ticker: "CLEBI", name: "Çelebi Hava Servisi", sector: "Ulaştırma" },
  { ticker: "CMBTN", name: "Çimbeton", sector: "Çimento & Yapı" },
  { ticker: "CMENT", name: "Çimentaş Çimento", sector: "Çimento & Yapı" },
  { ticker: "CONSE", name: "Consus Enerji", sector: "Enerji" },
  { ticker: "COSMO", name: "Cosmos Yatırım Holding", sector: "Holding" },
  { ticker: "CRDFA", name: "Creditwest Faktoring", sector: "Faktoring" },
  { ticker: "CRFSA", name: "CarrefourSA", sector: "Perakende" },
  { ticker: "CUSAN", name: "Çuhadaroğlu Metal", sector: "Metal & Alüminyum" },
  { ticker: "CVKMD", name: "CVK Madencilik", sector: "Madencilik" },
  { ticker: "CWENE", name: "CW Enerji", sector: "Enerji" },

  // D
  { ticker: "DAGI",  name: "Dagi Giyim", sector: "Tekstil / Perakende" },
  { ticker: "DAPGM", name: "DAP Gayrimenkul", sector: "Gayrimenkul" },
  { ticker: "DARDL", name: "Dardanel Önentaş Gıda", sector: "Gıda" },
  { ticker: "DENGE", name: "Denge Yatırım Holding", sector: "Holding" },
  { ticker: "DERHL", name: "Derlüks Yatırım Holding", sector: "Holding" },
  { ticker: "DERIM", name: "Derimod Konfeksiyon", sector: "Deri & Ayakkabı" },
  { ticker: "DESA",  name: "Desa Deri", sector: "Deri & Ayakkabı" },
  { ticker: "DESPC", name: "Despec Bilgisayar", sector: "Teknoloji" },
  { ticker: "DEVA",  name: "Deva Holding", sector: "Sağlık & İlaç" },
  { ticker: "DGATE", name: "Datagate Bilgisayar", sector: "Teknoloji" },
  { ticker: "DGGYO", name: "Doğuş GMYO", sector: "Gayrimenkul" },
  { ticker: "DGNMO", name: "Doğanlar Mobilya", sector: "Mobilya" },
  { ticker: "DITAS", name: "Ditaş Doğan Yedek Parça", sector: "Otomotiv Yan Sanayi" },
  { ticker: "DMRGD", name: "DMR Unlu Mamuller (Simit Sarayı)", sector: "Gıda" },
  { ticker: "DMSAS", name: "Demisaş Döküm", sector: "Döküm / Metal" },
  { ticker: "DNISI", name: "Dinamik Isı Makina", sector: "Yalıtım / İklimlendirme" },
  { ticker: "DOAS",  name: "Doğuş Otomotiv", sector: "Otomotiv" },
  { ticker: "DOBUR", name: "Doğan Burda Dergi", sector: "Medya" },
  { ticker: "DOCO",  name: "DO & CO", sector: "İkram / Gıda" },
  { ticker: "DOHOL", name: "Doğan Holding", sector: "Holding" },
  { ticker: "DOKTA", name: "Döktaş Dökümcülük", sector: "Döküm / Metal" },
  { ticker: "DURDO", name: "Duran Doğan Basım", sector: "Kağıt & Ambalaj" },
  { ticker: "DURKN", name: "Durukan Şekerleme", sector: "Gıda" },
  { ticker: "DYOBY", name: "Dyo Boya Fabrikaları", sector: "Kimya / Boya" },
  { ticker: "DZGYO", name: "Deniz GMYO", sector: "Gayrimenkul" },

  // E
  { ticker: "EBEBK", name: "Ebebek Mağazacılık", sector: "Perakende" },
  { ticker: "ECILC", name: "Eczacıbaşı İlaç", sector: "Sağlık & İlaç" },
  { ticker: "ECZYT", name: "Eczacıbaşı Yatırım", sector: "Holding" },
  { ticker: "EDATA", name: "E-Data Teknoloji", sector: "Teknoloji" },
  { ticker: "EDIP",  name: "Edip Gayrimenkul", sector: "Gayrimenkul" },
  { ticker: "EGEEN", name: "Ege Endüstri", sector: "Otomotiv Yan Sanayi" },
  { ticker: "EGEGY", name: "Ege GYO", sector: "Gayrimenkul" },
  { ticker: "EGGUB", name: "Ege Gübre", sector: "Kimya & Tarım" },
  { ticker: "EGPRO", name: "Ege Profil", sector: "Plastik & Yapı" },
  { ticker: "EGSER", name: "Ege Seramik", sector: "Seramik & Yapı" },
  { ticker: "EKGYO", name: "Emlak Konut GYO", sector: "Gayrimenkul" },
  { ticker: "EKOS",  name: "Ekos Teknoloji", sector: "Enerji & Teknoloji" },
  { ticker: "EKSUN", name: "Eksun Gıda", sector: "Gıda & Tarım" },
  { ticker: "ELITE", name: "Elite Naturel Organik Gıda", sector: "Gıda" },
  { ticker: "EMKEL", name: "Emek Elektrik", sector: "Elektrik & Enerji" },
  { ticker: "ENERY", name: "Enerya Enerji", sector: "Enerji" },
  { ticker: "ENJSA", name: "Enerjisa Enerji", sector: "Enerji" },
  { ticker: "ENKAI", name: "Enka İnşaat", sector: "Holding / İnşaat" },
  { ticker: "ENSRI", name: "Ensari Deri", sector: "Deri" },
  { ticker: "ENTRA", name: "IC Enterra Yenilenebilir Enerji", sector: "Enerji" },
  { ticker: "EPLAS", name: "Egeplast Ege Plastik", sector: "Plastik" },
  { ticker: "ERBOS", name: "Erbosan Boru", sector: "Demir Çelik" },
  { ticker: "ERCB",  name: "Erciyas Çelik Boru", sector: "Demir Çelik" },
  { ticker: "EREGL", name: "Ereğli Demir Çelik", sector: "Demir Çelik" },
  { ticker: "ERSU",  name: "Ersu Meyve Suları", sector: "Gıda & İçecek" },
  { ticker: "ESCAR", name: "Escar Filo Kiralama", sector: "Otomotiv / Filo" },
  { ticker: "ESCOM", name: "Escort Teknoloji", sector: "Teknoloji" },
  { ticker: "ESEN",  name: "Esenboğa Elektrik", sector: "Enerji" },
  { ticker: "ETILR", name: "Etiler Gıda", sector: "Gıda & İçecek" },
  { ticker: "EUPWR", name: "Europower Enerji", sector: "Enerji" },
  { ticker: "EUREN", name: "Europen Endüstri", sector: "Cam & Yapı" },
  { ticker: "EYGYO", name: "EYG GYO", sector: "Gayrimenkul" },

  // F
  { ticker: "FADE",  name: "Fade Gıda", sector: "Gıda & Tarım" },
  { ticker: "FENER", name: "Fenerbahçe Futbol", sector: "Spor" },
  { ticker: "FLAP",  name: "Flap Kongre Toplantı Hizmetleri", sector: "Turizm & Medya" },
  { ticker: "FMIZP", name: "Federal-Mogul İzmit Piston", sector: "Otomotiv Yan Sanayi" },
  { ticker: "FONET", name: "Fonet Bilgi Teknolojileri", sector: "Teknoloji" },
  { ticker: "FORMT", name: "Formet Metal ve Cam", sector: "Metal / Mobilya" },
  { ticker: "FORTE", name: "Forte Bilgi İletişim", sector: "Teknoloji" },
  { ticker: "FRIGO", name: "Frigo Pak Gıda", sector: "Gıda" },
  { ticker: "FROTO", name: "Ford Otosan", sector: "Otomotiv" },
  { ticker: "FZLGY", name: "Fuzul GYO", sector: "Gayrimenkul" },

  // G
  { ticker: "GARAN", name: "Garanti BBVA", sector: "Bankacılık" },
  { ticker: "GARFA", name: "Garanti Faktoring", sector: "Faktoring" },
  { ticker: "GEDIK", name: "Gedik Yatırım", sector: "Finansal Hizmetler" },
  { ticker: "GEDZA", name: "Gediz Ambalaj", sector: "Kağıt & Ambalaj" },
  { ticker: "GENIL", name: "Gen İlaç", sector: "Sağlık & İlaç" },
  { ticker: "GENTS", name: "Gentaş Genel Metal", sector: "Mobilya / Yapı" },
  { ticker: "GEREL", name: "Gersan Elektrik", sector: "Elektrik & Enerji" },
  { ticker: "GESAN", name: "Girişim Elektrik", sector: "Enerji" },
  { ticker: "GIPTA", name: "Gıpta Ofis Kırtasiye", sector: "İmalat / Kırtasiye" },
  { ticker: "GLBMD", name: "Global Menkul Değerler", sector: "Finansal Hizmetler" },
  { ticker: "GLCVY", name: "Gelecek Varlık Yönetimi", sector: "Finansal Hizmetler" },
  { ticker: "GLRYH", name: "Güler Yatırım Holding", sector: "Holding" },
  { ticker: "GLYHO", name: "Global Yatırım Holding", sector: "Holding" },
  { ticker: "GMTAS", name: "Gimat Mağazacılık", sector: "Perakende" },
  { ticker: "GOKNR", name: "Göknur Gıda", sector: "Gıda & Tarım" },
  { ticker: "GOLTS", name: "Göltaş Çimento", sector: "Çimento & Yapı" },
  { ticker: "GOODY", name: "Goodyear Lastikleri", sector: "Otomotiv" },
  { ticker: "GOZDE", name: "Gözde Girişim Sermayesi", sector: "Holding" },
  { ticker: "GRNYO", name: "Garanti Yatırım Ortaklığı", sector: "Menkul Kıymet YO" },
  { ticker: "GRSEL", name: "Gürsel Taşımacılık", sector: "Ulaştırma / Turizm" },
  { ticker: "GRTRK", name: "Graınturk Tarım", sector: "Tarım & Gıda" },
  { ticker: "GSDDE", name: "GSD Denizcilik", sector: "Denizcilik / Lojistik" },
  { ticker: "GSDHO", name: "GSD Holding", sector: "Holding" },
  { ticker: "GSRAY", name: "Galatasaray Sportif", sector: "Spor" },
  { ticker: "GUBRF", name: "Gübre Fabrikaları", sector: "Kimya & Tarım" },
  { ticker: "GWIND", name: "Galata Wind Enerji", sector: "Enerji" },
  { ticker: "GZNMI", name: "Gezinomi Seyahat", sector: "Turizm" },

  // H
  { ticker: "HALKB", name: "Halkbank", sector: "Bankacılık" },
  { ticker: "HATEK", name: "Hateks Hatay Tekstil", sector: "Tekstil" },
  { ticker: "HATSN", name: "Hatsan Gemi İnşa", sector: "Denizcilik / Savunma" },
  { ticker: "HDFGS", name: "Hedef Girişim Sermayesi", sector: "Finansal Hizmetler" },
  { ticker: "HEDEF", name: "Hedef Holding", sector: "Holding" },
  { ticker: "HEKTS", name: "Hektaş", sector: "Kimya & Tarım" },
  { ticker: "HKTM",  name: "Hidropar Hareket Kontrol", sector: "Mühendislik & Robotik" },
  { ticker: "HLGYO", name: "Halk GYO", sector: "Gayrimenkul" },
  { ticker: "HOROZ", name: "Horoz Lojistik", sector: "Lojistik" },
  { ticker: "HRKET", name: "Hareket Proje Taşımacılığı", sector: "Lojistik" },
  { ticker: "HTTBT", name: "Hitit Bilgisayar Hizmetleri", sector: "Teknoloji / Havacılık" },
  { ticker: "HUBVC", name: "Hub Girişim Sermayesi", sector: "Teknoloji Yatırımları" },
  { ticker: "HUNER", name: "Hun Yenilenebilir Enerji", sector: "Enerji" },
  { ticker: "HURGZ", name: "Hürriyet Gazetecilik", sector: "Medya" },

  // I - İ
  { ticker: "ICBCT", name: "ICBC Turkey Bank", sector: "Bankacılık" },
  { ticker: "IDGYO", name: "İdealist GYO", sector: "Gayrimenkul" },
  { ticker: "IEYHO", name: "Işıklar Enerji ve Yapı Holding", sector: "Holding" },
  { ticker: "IHAAS", name: "İhlas Haber Ajansı", sector: "Medya" },
  { ticker: "IHEVA", name: "İhlas Ev Aletleri", sector: "Dayanıklı Tüketim" },
  { ticker: "IHGZT", name: "İhlas Gazetecilik", sector: "Medya" },
  { ticker: "IHLAS", name: "İhlas Holding", sector: "Holding" },
  { ticker: "IHLGM", name: "İhlas Gayrimenkul", sector: "Gayrimenkul" },
  { ticker: "IHYAY", name: "İhlas Yayın Holding", sector: "Medya" },
  { ticker: "IMASM", name: "İmaş Makina", sector: "Makine / İmalat" },
  { ticker: "INDES", name: "İndeks Bilgisayar", sector: "Teknoloji" },
  { ticker: "INFO",  name: "İnfo Yatırım", sector: "Finansal Hizmetler" },
  { ticker: "INGRM", name: "Ingram Bilişim", sector: "Teknoloji" },
  { ticker: "INVES", name: "Investco Holding", sector: "Holding" },
  { ticker: "IPEKE", name: "İpek Doğal Enerji", sector: "Madencilik & Enerji" },
  { ticker: "ISBIR", name: "İşbir Sentetik Dokuma", sector: "Plastik & Tekstil" },
  { ticker: "ISCTR", name: "İş Bankası (C)", sector: "Bankacılık" },
  { ticker: "ISDMR", name: "İskenderun Demir Çelik", sector: "Demir Çelik" },
  { ticker: "ISFIN", name: "İş Finansal Kiralama", sector: "Finansal Kiralama" },
  { ticker: "ISGSY", name: "İş Girişim Sermayesi", sector: "Finansal Hizmetler" },
  { ticker: "ISGYO", name: "İş GYO", sector: "Gayrimenkul" },
  { ticker: "ISKPL", name: "Işık Plastik", sector: "Plastik" },
  { ticker: "ISMEN", name: "İş Yatırım Menkul Değerler", sector: "Finansal Hizmetler" },
  { ticker: "IZENR", name: "İzdemir Enerji", sector: "Enerji" },
  { ticker: "IZFAS", name: "İzmir Fırça", sector: "İmalat" },
  { ticker: "IZMDC", name: "İzmir Demir Çelik", sector: "Demir Çelik" },

  // J - K
  { ticker: "JANTS", name: "Jantsa Jant Sanayi", sector: "Otomotiv Yan Sanayi" },
  { ticker: "KAPLM", name: "Kaplamin Ambalaj", sector: "Kağıt & Ambalaj" },
  { ticker: "KAREL", name: "Karel Elektronik", sector: "Telekomünikasyon & Savunma" },
  { ticker: "KARSN", name: "Karsan Otomotiv", sector: "Otomotiv" },
  { ticker: "KARTN", name: "Kartonsan", sector: "Kağıt & Ambalaj" },
  { ticker: "KARYE", name: "Kartal Yenilenebilir Enerji", sector: "Enerji" },
  { ticker: "KATMR", name: "Katmerciler Ekipman", sector: "Savunma & Araç Üstü Ekipman" },
  { ticker: "KAYSE", name: "Kayseri Şeker Fabrikası", sector: "Gıda & Tarım" },
  { ticker: "KBORU", name: "Kuzey Boru", sector: "Plastik & Altyapı Boru" },
  { ticker: "KCAER", name: "Kocaer Çelik", sector: "Demir Çelik" },
  { ticker: "KCHOL", name: "Koç Holding", sector: "Holding" },
  { ticker: "KFEIN", name: "Kafein Yazılım", sector: "Teknoloji" },
  { ticker: "KGYO",  name: "Koray GYO", sector: "Gayrimenkul" },
  { ticker: "KIMMR", name: "Karsu Tekstil", sector: "Tekstil" },
  { ticker: "KLGYO", name: "Kiler GYO", sector: "Gayrimenkul" },
  { ticker: "KLKIM", name: "Kalekim Kimyevi Maddeler", sector: "Kimya / Yapı Malzemeleri" },
  { ticker: "KLMSN", name: "Klimasan Klima", sector: "İklimlendirme / Soğutma" },
  { ticker: "KLNMA", name: "Türkiye Kalkınma ve Yatırım Bankası", sector: "Bankacılık" },
  { ticker: "KLRHO", name: "Kiler Holding", sector: "Holding" },
  { ticker: "KLSER", name: "Kaleseramik", sector: "Seramik & Yapı" },
  { ticker: "KLSYN", name: "Koleksiyon Mobilya", sector: "Mobilya" },
  { ticker: "KMPUR", name: "Kimteks Poliüretan", sector: "Kimya" },
  { ticker: "KNFRT", name: "Konfrut Gıda", sector: "Gıda & Tarım" },
  { ticker: "KOCMT", name: "Koç Metalurji", sector: "Demir Çelik" },
  { ticker: "KONKA", name: "Konya Kağıt", sector: "Kağıt & Ambalaj" },
  { ticker: "KONTR", name: "Kontrolmatik Teknoloji", sector: "Teknoloji & Enerji" },
  { ticker: "KONYA", name: "Konya Çimento", sector: "Çimento & Yapı" },
  { ticker: "KOPOL", name: "Koza Polyester", sector: "Kimya / Elyaf" },
  { ticker: "KORDS", name: "Kordsa Teknik Tekstil", sector: "Kimya & Kompozit" },
  { ticker: "KOTON", name: "Koton Mağazacılık", sector: "Perakende" },
  { ticker: "KOZAA", name: "Koza Anadolu Metal", sector: "Madencilik" },
  { ticker: "TRALT", name: "Türk Altın İşletmeleri (Eski: KOZAL)", sector: "Madencilik" },
  { ticker: "KRDMD", name: "Kardemir (D)", sector: "Demir Çelik" },
  { ticker: "KRDMA", name: "Kardemir (A)", sector: "Demir Çelik" },
  { ticker: "KRDMB", name: "Kardemir (B)", sector: "Demir Çelik" },
  { ticker: "KRGYO", name: "Körfez GYO", sector: "Gayrimenkul" },
  { ticker: "KRONT", name: "Kron Telekomünikasyon", sector: "Teknoloji / Siber Güvenlik" },
  { ticker: "KRPLS", name: "Koroplast Temizlik Ambalaj", sector: "Ambalaj / Plastik" },
  { ticker: "KRSTL", name: "Kristal Kola", sector: "Gıda & İçecek" },
  { ticker: "KRTEK", name: "Karsu Tekstil", sector: "Tekstil" },
  { ticker: "KRVGD", name: "Kervan Gıda", sector: "Gıda & Şekerleme" },
  { ticker: "KSTUR", name: "Kuştur Kuşadası Turizm", sector: "Turizm" },
  { ticker: "KTLEV", name: "Katılımevim Tasarruf Finansman", sector: "Finansal Hizmetler" },
  { ticker: "KTSKR", name: "Kütahya Şeker", sector: "Gıda & Tarım" },
  { ticker: "KUTPO", name: "Kütahya Porselen", sector: "Porselen & Seramik" },
  { ticker: "KUYAS", name: "Kuyas Yatırım", sector: "Gayrimenkul" },
  { ticker: "KZBGY", name: "Kızılbük GYO", sector: "Gayrimenkul" },
  { ticker: "KZGYO", name: "Kuzugrup GYO", sector: "Gayrimenkul" },

  // L
  { ticker: "LIDER", name: "Lider Filo Kiralama", sector: "Otomotiv / Filo" },
  { ticker: "LIDFA", name: "Lider Faktoring", sector: "Faktoring" },
  { ticker: "LILAK", name: "Lila Kağıt", sector: "Kağıt & Ambalaj" },
  { ticker: "LINK",  name: "Link Bilgisayar", sector: "Teknoloji" },
  { ticker: "LKMNH", name: "Lokman Hekim Sağlık", sector: "Sağlık" },
  { ticker: "LMKDC", name: "Limak Doğu Anadolu Çimento", sector: "Çimento & Yapı" },
  { ticker: "LOGO",  name: "Logo Yazılım", sector: "Teknoloji" },
  { ticker: "LUKSK", name: "Lüks Kadife", sector: "Tekstil" },

  // M
  { ticker: "MAALT", name: "Marmaris Altınyunus", sector: "Turizm" },
  { ticker: "MACKO", name: "Mackolik İnternet Hizmetleri", sector: "Teknoloji / Medya" },
  { ticker: "MAGEN", name: "Margün Enerji", sector: "Enerji" },
  { ticker: "MAKIM", name: "Makim Makine", sector: "Hassas Döküm / Savunma" },
  { ticker: "MAKTK", name: "Makina Takım", sector: "Hırdavat / Makine" },
  { ticker: "MANAS", name: "Manas Enerji Yönetimi", sector: "Teknoloji & Sayaç" },
  { ticker: "MARBL", name: "Tureks Turunç Madencilik", sector: "Mermer & Madencilik" },
  { ticker: "MARTI", name: "Martı Otel İşletmeleri", sector: "Turizm" },
  { ticker: "MAVI",  name: "Mavi Giyim", sector: "Perakende" },
  { ticker: "MEDTR", name: "Meditera Tıbbi Malzeme", sector: "Sağlık" },
  { ticker: "MEGAP", name: "Mega Polietilen", sector: "Kimya / Tekstil" },
  { ticker: "MEGMT", name: "Mega Metal", sector: "Metal / Bakır Tel" },
  { ticker: "MEKAG", name: "Meka Beton Santralleri", sector: "Makine & İmalat" },
  { ticker: "MEPET", name: "Mepet Metro Petrol", sector: "Akaryakıt / Hizmet" },
  { ticker: "MERCN", name: "Mercan Kimya", sector: "Kimya" },
  { ticker: "MERIT", name: "Merit Turizm", sector: "Turizm" },
  { ticker: "MERKO", name: "Merko Gıda", sector: "Gıda" },
  { ticker: "METRO", name: "Metro Ticari ve Mali Yatırımlar", sector: "Holding" },
  { ticker: "METUR", name: "Metemtur Yatırım", sector: "Turizm" },
  { ticker: "MEYRA", name: "Meyra Madencilik", sector: "Madencilik" },
  { ticker: "MGENR", name: "Margün Enerji", sector: "Enerji" },
  { ticker: "MGROS", name: "Migros Ticaret", sector: "Perakende" },
  { ticker: "MIATK", name: "Mia Teknoloji", sector: "Teknoloji" },
  { ticker: "MIPAZ", name: "Milpa Ticari Yatırımlar", sector: "Holding" },
  { ticker: "MNDRS", name: "Menderes Tekstil", sector: "Tekstil & Enerji" },
  { ticker: "MNDTR", name: "Mondi Turkey Oluklu Mukavva", sector: "Kağıt & Ambalaj" },
  { ticker: "MOBTL", name: "Mobiltel İletişim", sector: "Teknoloji / İletişim" },
  { ticker: "MOGAN", name: "Mogan Enerji", sector: "Enerji" },
  { ticker: "MPARK", name: "MLP Sağlık (Medical Park)", sector: "Sağlık" },
  { ticker: "MRGYO", name: "Martı GYO", sector: "Gayrimenkul" },
  { ticker: "MRSHL", name: "Marshall Boya", sector: "Kimya / Boya" },
  { ticker: "MSGYO", name: "Mistral GYO", sector: "Gayrimenkul" },
  { ticker: "MTRKS", name: "Matriks Bilgi Dağıtım", sector: "Fintech / Bilişim" },
  { ticker: "MTRYO", name: "Metro Yatırım Ortaklığı", sector: "Menkul Kıymet YO" },

  // N - O
  { ticker: "NATEN", name: "Naturel Yenilenebilir Enerji", sector: "Enerji" },
  { ticker: "NETAS", name: "Netaş Telekomünikasyon", sector: "Teknoloji" },
  { ticker: "NIBAS", name: "Niğbaş Niğde Beton", sector: "Beton / Yapı" },
  { ticker: "NTGAZ", name: "Naturelgaz", sector: "Enerji / Gaz" },
  { ticker: "NTHOL", name: "Net Holding", sector: "Holding / Turizm" },
  { ticker: "NUGYO", name: "Nurol GYO", sector: "Gayrimenkul" },
  { ticker: "NUHCM", name: "Nuh Çimento", sector: "Çimento & Yapı" },
  { ticker: "OBAMS", name: "Oba Makarnacılık", sector: "Gıda & Tarım" },
  { ticker: "OBASE", name: "Obase Bilgisayar", sector: "Teknoloji" },
  { ticker: "ODAS",  name: "Odaş Elektrik", sector: "Enerji & Madencilik" },
  { ticker: "ODINE", name: "Odine Solutions Teknoloji", sector: "Teknoloji" },
  { ticker: "OFSYM", name: "Ofis Yem Gıda", sector: "Tarım & Yem" },
  { ticker: "ONCSM", name: "Oncosem Onkolojik Sistemler", sector: "Sağlık" },
  { ticker: "ORCAY", name: "Orçay Ortaköy Çay", sector: "Gıda" },
  { ticker: "ORGE",  name: "Orge Elektrik Taahhüt", sector: "Elektrik Taahhüt" },
  { ticker: "ORMA",  name: "Orma Orman Mamulleri", sector: "Ağaç / Orman" },
  { ticker: "OSMEN", name: "Osmanlı Yatırım", sector: "Finansal Hizmetler" },
  { ticker: "OSTIM", name: "Ostim Endüstriyel Yatırımlar", sector: "Sanayi / Yatırım" },
  { ticker: "OTKAR", name: "Otokar Savunma ve Otomotiv", sector: "Otomotiv & Savunma" },
  { ticker: "OTTO",  name: "Otto Holding", sector: "Holding" },
  { ticker: "OYAKC", name: "Oyak Çimento", sector: "Çimento & Yapı" },
  { ticker: "OYAYO", name: "Oyak Yatırım Ortaklığı", sector: "Menkul Kıymet YO" },
  { ticker: "OYLUM", name: "Oylum Bisküvi", sector: "Gıda" },
  { ticker: "OYYAT", name: "Oyak Yatırım Menkul Değerler", sector: "Finansal Hizmetler" },
  { ticker: "OZATD", name: "Özata Denizcilik", sector: "Tersane & Denizcilik" },
  { ticker: "OZGYO", name: "Özderici GYO", sector: "Gayrimenkul" },
  { ticker: "OZKGY", name: "Özak GYO", sector: "Gayrimenkul" },
  { ticker: "OZRDN", name: "Özerden Plastik", sector: "Ambalaj / Plastik" },
  { ticker: "OZSUB", name: "Özsu Balık Üretim", sector: "Su Ürünleri / Gıda" },

  // P - Q - R
  { ticker: "PAGYO", name: "Panora GYO", sector: "Gayrimenkul" },
  { ticker: "PAMEL", name: "Pamukova Yenilenebilir Enerji", sector: "Enerji" },
  { ticker: "PAPIL", name: "Papilon Savunma Güvenlik", sector: "Biyometri & Savunma" },
  { ticker: "PARSN", name: "Parsan Makina Parçaları", sector: "Dövme Çelik / Otomotiv" },
  { ticker: "PASEU", name: "Pasifik Eurasia Lojistik", sector: "Lojistik" },
  { ticker: "PATEK", name: "Pasifik Donanım Yazılım", sector: "Teknoloji" },
  { ticker: "PCILT", name: "PC İletişim Medya", sector: "Medya / Reklam" },
  { ticker: "PEKGY", name: "Peker GYO", sector: "Gayrimenkul" },
  { ticker: "PENGD", name: "Penguen Gıda", sector: "Gıda" },
  { ticker: "PENTA", name: "Penta Teknoloji Dağıtım", sector: "Teknoloji" },
  { ticker: "PETKM", name: "Petkim Petrokimya", sector: "Petrokimya" },
  { ticker: "PETUN", name: "Pınar Et ve Un", sector: "Gıda" },
  { ticker: "PGSUS", name: "Pegasus Hava Yolları", sector: "Ulaştırma" },
  { ticker: "PINSU", name: "Pınar Su", sector: "İçecek" },
  { ticker: "PKART", name: "Plastikkart Akıllı Kart", sector: "Akıllı Kart / Teknoloji" },
  { ticker: "PKENT", name: "Petrokent Turizm", sector: "Turizm" },
  { ticker: "PLTUR", name: "Platform Turizm Taşımacılık", sector: "Ulaştırma / Turizm" },
  { ticker: "PNLSN", name: "Panelsan Çatı Cephe", sector: "Yapı Malzemeleri" },
  { ticker: "PNSUT", name: "Pınar Süt", sector: "Gıda" },
  { ticker: "POLHO", name: "Polisan Holding", sector: "Kimya & Boya" },
  { ticker: "POLTK", name: "Politeknik Metal", sector: "Alüminyum & Kimya" },
  { ticker: "PRDGS", name: "Pardus Girişim Sermayesi", sector: "Girişim Sermayesi" },
  { ticker: "PRKAB", name: "Türk Prysmian Kablo", sector: "Kablo / Telekom" },
  { ticker: "PRKME", name: "Park Elektrik Madencilik", sector: "Madencilik & Enerji" },
  { ticker: "PRZMA", name: "Prizma Pres Matbaacılık", sector: "Matbaa" },
  { ticker: "PSDTC", name: "Pera Gayrimenkul Yatırım", sector: "Gayrimenkul" },
  { ticker: "PSGYO", name: "Pasifik GYO", sector: "Gayrimenkul" },
  { ticker: "QNBFB", name: "QNB Finansbank", sector: "Bankacılık" },
  { ticker: "QNBFL", name: "QNB Finans Finansal Kiralama", sector: "Leasing" },
  { ticker: "QUAGR", name: "Qua Granite Hayal Yapı", sector: "Seramik & Yapı" },
  { ticker: "RALYH", name: "Ral Yatırım Holding", sector: "Holding / İnşaat" },
  { ticker: "RAYSG", name: "Ray Sigorta", sector: "Sigortacılık" },
  { ticker: "REEDR", name: "Reeder Teknoloji", sector: "Tüketici Elektroniği" },
  { ticker: "RNPOL", name: "Rainbow Polikarbonat", sector: "Plastik & Yapı" },
  { ticker: "RODRG", name: "Rodrigo Tekstil", sector: "Tekstil" },
  { ticker: "RTALB", name: "RTA Laboratuvarları", sector: "Biyoteknoloji & Sağlık" },
  { ticker: "RUBNS", name: "Rubenis Mensucat", sector: "Tekstil" },
  { ticker: "RYGYO", name: "Reysaş GYO", sector: "Lojistik GYO" },
  { ticker: "RYSAS", name: "Reysaş Taşımacılık", sector: "Lojistik" },

  // S - Ş
  { ticker: "SAFKR", name: "Safkar Ege Soğutmacılık", sector: "İklimlendirme" },
  { ticker: "SAHOL", name: "Sabancı Holding", sector: "Holding" },
  { ticker: "SAMAT", name: "Saray Matbaacılık", sector: "Matbaa" },
  { ticker: "SANEL", name: "San-El Mühendislik", sector: "Elektrik Mühendisliği" },
  { ticker: "SANFM", name: "Sanifoam Sünger", sector: "Sünger / İmalat" },
  { ticker: "SANKO", name: "Sanko Pazarlama İthalat", sector: "Tekstil" },
  { ticker: "SARKY", name: "Sarkuysan Elektrolitik Bakır", sector: "Bakır / Metal" },
  { ticker: "SASA",  name: "Sasa Polyester", sector: "Kimya / Polyester" },
  { ticker: "SAYAS", name: "Say Yenilenebilir Enerji", sector: "Yenilenebilir Ekipman" },
  { ticker: "SDTTR", name: "SDT Uzay ve Savunma", sector: "Savunma & Uzay" },
  { ticker: "SEGYO", name: "Şeker GYO", sector: "Gayrimenkul" },
  { ticker: "SEKFK", name: "Şeker Finansal Kiralama", sector: "Leasing" },
  { ticker: "SEKUR", name: "Sekuro Plastik", sector: "Plastik & Ambalaj" },
  { ticker: "SELEC", name: "Selçuk Ecza Deposu", sector: "İlaç Dağıtım" },
  { ticker: "SELGD", name: "Selçuk Gıda", sector: "Gıda" },
  { ticker: "SELVA", name: "Selva Gıda", sector: "Gıda" },
  { ticker: "SEYKM", name: "Seyitler Kimya", sector: "Tıbbi Malzeme / Kimya" },
  { ticker: "SILVR", name: "Silverline Endüstri", sector: "Ankastre / Dayanıklı Tüketim" },
  { ticker: "SISE",  name: "Şişecam", sector: "Cam & Kimya" },
  { ticker: "SKBNK", name: "Şekerbank", sector: "Bankacılık" },
  { ticker: "SKTAS", name: "Söktaş Tekstil", sector: "Tekstil" },
  { ticker: "SMART", name: "Smartiks Yazılım", sector: "Teknoloji" },
  { ticker: "SMRTG", name: "Smart Güneş Enerjisi", sector: "Güneş Enerjisi" },
  { ticker: "SNGYO", name: "Sinpaş GYO", sector: "Gayrimenkul" },
  { ticker: "SNICA", name: "Sanica Isı Sanayi", sector: "Radyatör / Isı" },
  { ticker: "SOKE",  name: "Söke Değirmencilik", sector: "Gıda & Un" },
  { ticker: "SOKM",  name: "Şok Marketler", sector: "Perakende" },
  { ticker: "SONME", name: "Sönmez Filament", sector: "Tekstil / Yatırım" },
  { ticker: "SRVGY", name: "Servet GYO", sector: "Gayrimenkul" },
  { ticker: "SUMAS", name: "Sumaş Suni Tahta", sector: "Ağaç / Orman" },
  { ticker: "SUNTK", name: "Sun Tekstil", sector: "Tekstil" },
  { ticker: "SURGY", name: "Sur Tatil Evleri GYO", sector: "Gayrimenkul" },
  { ticker: "SUWEN", name: "Suwen Tekstil", sector: "Perakende" },

  // T
  { ticker: "TABGD", name: "TAB Gıda", sector: "Hızlı Servis Restoran" },
  { ticker: "TARKM", name: "Tarkim Bitki Koruma", sector: "Zirai İlaç / Tarım" },
  { ticker: "TATEN", name: "Tatlıpınar Enerji", sector: "Rüzgar & Güneş Enerjisi" },
  { ticker: "TATGD", name: "Tat Gıda", sector: "Gıda" },
  { ticker: "TAVHL", name: "TAV Havalimanları", sector: "Havalimanı İşletmeciliği" },
  { ticker: "TBORG", name: "Türk Tuborg", sector: "İçecek" },
  { ticker: "TCELL", name: "Turkcell", sector: "Telekomünikasyon" },
  { ticker: "TDGYO", name: "Trend GYO", sector: "Gayrimenkul" },
  { ticker: "TEKTU", name: "Tek-Art Turizm", sector: "Turizm" },
  { ticker: "TERA",  name: "Tera Yatırım Menkul Değerler", sector: "Finansal Hizmetler" },
  { ticker: "TETMT", name: "Tetamat Gıda", sector: "Gıda" },
  { ticker: "TEZOL", name: "Europap Tezol Kağıt", sector: "Temizlik Kağıdı" },
  { ticker: "THYAO", name: "Türk Hava Yolları", sector: "Havacılık / Ulaştırma" },
  { ticker: "TKFEN", name: "Tekfen Holding", sector: "Holding / Taahhüt" },
  { ticker: "TKNSA", name: "Teknosa", sector: "Elektronik Perakende" },
  { ticker: "TLMAN", name: "Trabzon Liman İşletmeciliği", sector: "Liman / Lojistik" },
  { ticker: "TMPOL", name: "Temapol Polimer Plastik", sector: "Plastik" },
  { ticker: "TMSN",  name: "Tümosan Motor ve Traktör", sector: "Traktör & Savunma" },
  { ticker: "TNZTP", name: "Tapdi Oksijen (Tınaztepe)", sector: "Sağlık" },
  { ticker: "TOASO", name: "Tofaş Türk Otomobil Fabrikası", sector: "Otomotiv" },
  { ticker: "TRCAS", name: "Turcas Petrol", sector: "Enerji / Petrol" },
  { ticker: "TRGYO", name: "Torunlar GYO", sector: "Gayrimenkul" },
  { ticker: "TRILC", name: "Türk İlaç ve Serum Sanayi", sector: "İlaç & Aşı" },
  { ticker: "TSKB",  name: "Türkiye Sınai Kalkınma Bankası", sector: "Kalkınma Bankacılığı" },
  { ticker: "TSPOR", name: "Trabzonspor Sportif", sector: "Spor" },
  { ticker: "TTKOM", name: "Türk Telekom", sector: "Telekomünikasyon" },
  { ticker: "TTRAK", name: "Türk Traktör", sector: "Tarım Makineleri" },
  { ticker: "TUCLK", name: "Tuğçelik Alüminyum ve Metal", sector: "Alüminyum Döküm" },
  { ticker: "TUKAS", name: "Tukaş Gıda", sector: "Gıda & Konserve" },
  { ticker: "TUPRS", name: "Tüpraş Türkiye Petrol Rafinerileri", sector: "Petrol Rafinajı" },
  { ticker: "TUREX", name: "Tureks Turizm Taşımacılık", sector: "Ulaşım / Servis" },
  { ticker: "TURGG", name: "Türker Proje Gayrimenkul", sector: "Gayrimenkul" },
  { ticker: "TURSG", name: "Türkiye Sigorta", sector: "Sigortacılık" },

  // U - Ü - V
  { ticker: "UFUK",  name: "Ufuk Yatırım", sector: "Yatırım" },
  { ticker: "ULAS",  name: "Ulaşlar Turizm Yatırımları", sector: "Turizm" },
  { ticker: "ULFAK", name: "Ulusal Faktoring", sector: "Faktoring" },
  { ticker: "ULKER", name: "Ülker Bisküvi", sector: "Gıda & Atıştırmalık" },
  { ticker: "UNLU",  name: "Ünlü Yatırım Holding", sector: "Yatırım Bankacılığı" },
  { ticker: "USAK",  name: "Uşak Seramik", sector: "Seramik & Karo" },
  { ticker: "VAKBN", name: "VakıfBank", sector: "Bankacılık" },
  { ticker: "VAKFN", name: "Vakıf Finansal Kiralama", sector: "Leasing" },
  { ticker: "VAKKO", name: "Vakko Tekstil", sector: "Lüks Giyim" },
  { ticker: "VANGD", name: "Vanet Gıda", sector: "Gıda" },
  { ticker: "VBTYZ", name: "VBT Yazılım", sector: "Bilişim & Yazılım" },
  { ticker: "VERTU", name: "Verusaturk Girişim Sermayesi", sector: "Girişim Sermayesi" },
  { ticker: "VERUS", name: "Verusa Holding", sector: "Holding" },
  { ticker: "VESBE", name: "Vestel Beyaz Eşya", sector: "Beyaz Eşya" },
  { ticker: "VESTL", name: "Vestel Elektronik", sector: "Tüketici Elektroniği" },
  { ticker: "VKFYO", name: "Vakıf Menkul Kıymet YO", sector: "Menkul Kıymet YO" },
  { ticker: "VKGYO", name: "Vakıf GYO", sector: "Gayrimenkul" },
  { ticker: "VKING", name: "Viking Kağıt", sector: "Kağıt" },
  { ticker: "VRGYO", name: "Vera Konsept GYO", sector: "Gayrimenkul" },

  // Y - Z
  { ticker: "YAPRK", name: "Yaprak Süt ve Besi", sector: "Hayvancılık & Süt" },
  { ticker: "YATAS", name: "Yataş Yatak ve Yorgan", sector: "Mobilya & Yatak" },
  { ticker: "YAYLA", name: "Yayla Enerji Üretim", sector: "Enerji & Taahhüt" },
  { ticker: "YGGYO", name: "Yeni Gimat GYO (Ankamall)", sector: "Gayrimenkul" },
  { ticker: "YGYO",  name: "Yeşil GYO", sector: "Gayrimenkul" },
  { ticker: "YKBNK", name: "Yapı ve Kredi Bankası", sector: "Bankacılık" },
  { ticker: "YKSLN", name: "Yükselen Çelik", sector: "Vasıflı Çelik" },
  { ticker: "YONGA", name: "Yonga Mobilya", sector: "Masif Mobilya" },
  { ticker: "YUNSA", name: "Yünsa Yünlü Sanayi", sector: "Yünlü Kumaş" },
  { ticker: "YYAPI", name: "Yeşil Yapı Endüstrisi", sector: "İnşaat" },
  { ticker: "YYLGD", name: "Yayla Agro Gıda", sector: "Bakliyat & Gıda" },
  { ticker: "ZEDUR", name: "Zedur Enerji", sector: "Yenilenebilir Enerji" },
  { ticker: "ZOREN", name: "Zorlu Enerji", sector: "Enerji" },
  { ticker: "ZRGYO", name: "Ziraat GYO", sector: "Gayrimenkul" },
];
