/**
 * Borsa İstanbul (BIST) Tüm Hisseler ve Sektör Kataloğu
 */

export interface BISTStock {
  ticker: string;
  name: string;
  sector: string;
}

export const ALL_BIST_STOCKS: BISTStock[] = [
  // Bankacılık
  { ticker: "AKBNK", name: "Akbank", sector: "Bankacılık" },
  { ticker: "GARAN", name: "Garanti BBVA", sector: "Bankacılık" },
  { ticker: "ISCTR", name: "İş Bankası (C)", sector: "Bankacılık" },
  { ticker: "YKBNK", name: "Yapı Kredi Bankası", sector: "Bankacılık" },
  { ticker: "VAKBN", name: "Vakıflar Bankası", sector: "Bankacılık" },
  { ticker: "HALKB", name: "Halkbank", sector: "Bankacılık" },
  { ticker: "TSKB",  name: "T.S.K.B.", sector: "Bankacılık" },
  { ticker: "ALBRK", name: "Albaraka Türk", sector: "Bankacılık" },
  { ticker: "QNBFB", name: "QNB Finansbank", sector: "Bankacılık" },
  { ticker: "KLNMA", name: "Kalkınma Bankası", sector: "Bankacılık" },

  // Holding & Yatırım
  { ticker: "KCHOL", name: "Koç Holding", sector: "Holding" },
  { ticker: "SAHOL", name: "Sabancı Holding", sector: "Holding" },
  { ticker: "ALARK", name: "Alarko Holding", sector: "Holding" },
  { ticker: "DOHOL", name: "Doğan Holding", sector: "Holding" },
  { ticker: "AGHOL", name: "Anadolu Grubu Holding", sector: "Holding" },
  { ticker: "ENKAI", name: "Enka İnşaat / Holding", sector: "Holding" },
  { ticker: "TEKFEN", name: "Tekfen Holding", sector: "Holding" },
  { ticker: "BERA",  name: "Bera Holding", sector: "Holding" },
  { ticker: "GSDHO", name: "GSD Holding", sector: "Holding" },
  { ticker: "GOZDE", name: "Gözde Girişim", sector: "Holding" },
  { ticker: "VERUS", name: "Verusa Holding", sector: "Holding" },
  { ticker: "BINHO", name: "1000 Yatırımlar Holding", sector: "Holding" },

  // Havacılık & Ulaştırma & Lojistik
  { ticker: "THYAO", name: "Türk Hava Yolları", sector: "Ulaştırma" },
  { ticker: "PGSUS", name: "Pegasus Hava Yolları", sector: "Ulaştırma" },
  { ticker: "TAVHL", name: "TAV Havalimanları", sector: "Ulaştırma" },
  { ticker: "CLEBI", name: "Çelebi Hava Servisi", sector: "Ulaştırma" },
  { ticker: "RYSAS", name: "Reysaş Lojistik", sector: "Lojistik" },
  { ticker: "PASEU", name: "Pasifik Eurasia Lojistik", sector: "Lojistik" },
  { ticker: "TLMAN", name: "Trabzon Liman", sector: "Lojistik" },
  { ticker: "HRKET", name: "Hareket Proje Taşımacılığı", sector: "Lojistik" },

  // Enerji, Petrol & Gaz
  { ticker: "TUPRS", name: "Tüpraş", sector: "Enerji" },
  { ticker: "ASTOR", name: "Astor Enerji", sector: "Enerji" },
  { ticker: "EUPWR", name: "Europower Enerji", sector: "Enerji" },
  { ticker: "CWENE", name: "CW Enerji", sector: "Enerji" },
  { ticker: "ALFAS", name: "Alfa Solar Enerji", sector: "Enerji" },
  { ticker: "SMRTG", name: "Smart Güneş Enerjisi", sector: "Enerji" },
  { ticker: "KONTR", name: "Kontrolmatik Teknoloji", sector: "Enerji" },
  { ticker: "ENJSA", name: "Enerjisa Enerji", sector: "Enerji" },
  { ticker: "GWIND", name: "Galata Wind Enerji", sector: "Enerji" },
  { ticker: "AKSEN", name: "Aksa Enerji", sector: "Enerji" },
  { ticker: "AYDEM", name: "Aydem Yenilenebilir Enerji", sector: "Enerji" },
  { ticker: "CANTE", name: "Çan2 Termik", sector: "Enerji" },
  { ticker: "ENTRA", name: "IC Enterra Yenilenebilir Enerji", sector: "Enerji" },
  { ticker: "ODAS",  name: "Odaş Elektrik", sector: "Enerji" },
  { ticker: "ZOREN", name: "Zorlu Enerji", sector: "Enerji" },
  { ticker: "BIOEN", name: "Biotrend Çevre ve Enerji", sector: "Enerji" },
  { ticker: "TATEN", name: "Tatlupınar Enerji", sector: "Enerji" },
  { ticker: "IZENR", name: "İzdemir Enerji", sector: "Enerji" },
  { ticker: "AHGAZ", name: "Ahlatcı Doğalgaz", sector: "Enerji" },

  // Demir Çelik & Metal
  { ticker: "EREGL", name: "Ereğli Demir Çelik", sector: "Demir Çelik" },
  { ticker: "ISDMR", name: "İskenderun Demir Çelik", sector: "Demir Çelik" },
  { ticker: "KRDMD", name: "Kardemir (D)", sector: "Demir Çelik" },
  { ticker: "KRDMA", name: "Kardemir (A)", sector: "Demir Çelik" },
  { ticker: "KRDMB", name: "Kardemir (B)", sector: "Demir Çelik" },
  { ticker: "KCAER", name: "Kocaer Çelik", sector: "Demir Çelik" },
  { ticker: "CEMTS", name: "Çemtaş", sector: "Demir Çelik" },
  { ticker: "IZMDC", name: "İzmir Demir Çelik", sector: "Demir Çelik" },
  { ticker: "SARKY", name: "Sarkuysan Elektrolitik Bakır", sector: "Metal" },
  { ticker: "TUCLK", name: "Tuğçelik Alüminyum", sector: "Metal" },

  // Otomotiv & Yan Sanayi
  { ticker: "FROTO", name: "Ford Otosan", sector: "Otomotiv" },
  { ticker: "TOASO", name: "Tofaş Oto", sector: "Otomotiv" },
  { ticker: "DOAS",  name: "Doğuş Otomotiv", sector: "Otomotiv" },
  { ticker: "TTRAK", name: "Türk Traktör", sector: "Otomotiv" },
  { ticker: "OTKAR", name: "Otokar", sector: "Otomotiv" },
  { ticker: "BRISA", name: "Brisa Lastik", sector: "Otomotiv" },
  { ticker: "GOODY", name: "Goodyear Lastikleri", sector: "Otomotiv" },
  { ticker: "ASUZU", name: "Anadolu Isuzu", sector: "Otomotiv" },
  { ticker: "KARSN", name: "Karsan Otomotiv", sector: "Otomotiv" },
  { ticker: "TMSN",  name: "Tümosan Motor", sector: "Otomotiv" },
  { ticker: "EGEEN", name: "Ege Endüstri", sector: "Otomotiv" },
  { ticker: "BFREN", name: "Bosch Fren Sistemleri", sector: "Otomotiv" },
  { ticker: "JANTS", name: "Jantsa Jant Sanayi", sector: "Otomotiv" },

  // Perakende, Tüketim & Mağazacılık
  { ticker: "BIMAS", name: "BİM Birleşik Mağazalar", sector: "Perakende" },
  { ticker: "MGROS", name: "Migros Ticaret", sector: "Perakende" },
  { ticker: "SOKM",  name: "Şok Marketler", sector: "Perakende" },
  { ticker: "EBEBK", name: "Ebebek Mağazacılık", sector: "Perakende" },
  { ticker: "KOTON", name: "Koton Mağazacılık", sector: "Perakende" },
  { ticker: "MAVI",  name: "Mavi Giyim", sector: "Perakende" },
  { ticker: "VAKKO", name: "Vakko Tekstil", sector: "Perakende" },
  { ticker: "SUWEN", name: "Suwen Tekstil", sector: "Perakende" },
  { ticker: "BIZIM", name: "Bizim Toptan Satış", sector: "Perakende" },
  { ticker: "TKNSA", name: "Teknosa İç ve Dış Ticaret", sector: "Perakende" },

  // Gıda & İçecek
  { ticker: "CCOLA", name: "Coca-Cola İçecek", sector: "Gıda & İçecek" },
  { ticker: "AEFES", name: "Anadolu Efes", sector: "Gıda & İçecek" },
  { ticker: "ULKER", name: "Ülker Bisküvi", sector: "Gıda & İçecek" },
  { ticker: "TABGD", name: "TAB Gıda", sector: "Gıda & İçecek" },
  { ticker: "OBAMS", name: "Oba Makarnacılık", sector: "Gıda & İçecek" },
  { ticker: "SOKE",  name: "Söke Değirmencilik", sector: "Gıda & İçecek" },
  { ticker: "GOKNR", name: "Göknur Gıda", sector: "Gıda & İçecek" },
  { ticker: "BORSK", name: "Bor Şeker", sector: "Gıda & İçecek" },
  { ticker: "KAYSE", name: "Kayseri Şeker Fabrikası", sector: "Gıda & İçecek" },
  { ticker: "EKSUN", name: "Eksun Gıda", sector: "Gıda & İçecek" },
  { ticker: "TATGD", name: "Tat Gıda", sector: "Gıda & İçecek" },
  { ticker: "TUKAS", name: "Tukaş Gıda", sector: "Gıda & İçecek" },
  { ticker: "PNSUT", name: "Pınar Süt", sector: "Gıda & İçecek" },
  { ticker: "PETUN", name: "Pınar Et ve Un", sector: "Gıda & İçecek" },
  { ticker: "BANVT", name: "Banvit Bandırma Vitaminli Yem", sector: "Gıda & İçecek" },
  { ticker: "KRVGD", name: "Kervan Gıda", sector: "Gıda & İçecek" },
  { ticker: "DARDL", name: "Dardanel Önentaş Gıda", sector: "Gıda & İçecek" },
  { ticker: "BYDNR", name: "Baydöner Restoranları", sector: "Gıda & İçecek" },
  { ticker: "BIGCH", name: "BigChefs (Büyük Şefler)", sector: "Gıda & İçecek" },

  // Savunma, Teknoloji & Bilişim
  { ticker: "ASELS", name: "Aselsan", sector: "Savunma" },
  { ticker: "SDTTR", name: "SDT Uzay ve Savunma", sector: "Savunma" },
  { ticker: "MIATK", name: "Mia Teknoloji", sector: "Teknoloji" },
  { ticker: "REEDR", name: "Reeder Teknoloji", sector: "Teknoloji" },
  { ticker: "AGROT", name: "Agrotech Yüksek Teknoloji", sector: "Teknoloji" },
  { ticker: "ODINE", name: "Odine Solutions Teknoloji", sector: "Teknoloji" },
  { ticker: "FORTE", name: "Forte Bilgi İletişim", sector: "Teknoloji" },
  { ticker: "FONET", name: "Fonet Bilgi Teknolojileri", sector: "Teknoloji" },
  { ticker: "VBTYZ", name: "VBT Yazılım", sector: "Teknoloji" },
  { ticker: "LOGO",  name: "Logo Yazılım", sector: "Teknoloji" },
  { ticker: "ARDYZ", name: "Ardyz Bilişim", sector: "Teknoloji" },
  { ticker: "KFEIN", name: "Kafein Yazılım", sector: "Teknoloji" },
  { ticker: "PENTA", name: "Penta Teknoloji", sector: "Teknoloji" },
  { ticker: "INDES", name: "İndeks Bilgisayar", sector: "Teknoloji" },
  { ticker: "NETAS", name: "Netaş Telekomünikasyon", sector: "Teknoloji" },
  { ticker: "MOBTL", name: "Mobiltel İletişim", sector: "Teknoloji" },
  { ticker: "MTRKS", name: "Matriks Bilgi Dağıtım", sector: "Teknoloji" },
  { ticker: "PAPIL", name: "Papilon Savunma", sector: "Teknoloji" },
  { ticker: "ATATP", name: "ATP Ticari Bilgisayar", sector: "Teknoloji" },
  { ticker: "OBASE", name: "Obase Bilgisayar", sector: "Teknoloji" },

  // Telekomünikasyon
  { ticker: "TCELL", name: "Turkcell", sector: "Telekomünikasyon" },
  { ticker: "TTKOM", name: "Türk Telekom", sector: "Telekomünikasyon" },

  // Kimya, Petrol, Plastik & Cam
  { ticker: "SISE",  name: "Şişecam", sector: "Cam & Kimya" },
  { ticker: "PETKM", name: "Petkim", sector: "Kimya" },
  { ticker: "AKSA",  name: "Aksa Akrilik", sector: "Kimya" },
  { ticker: "HEKTS", name: "Hektaş", sector: "Kimya & Tarım" },
  { ticker: "GUBRF", name: "Gübre Fabrikaları", sector: "Kimya & Tarım" },
  { ticker: "BAGFS", name: "Bağfaş Bandırma Gübre", sector: "Kimya & Tarım" },
  { ticker: "KMPUR", name: "Kimteks Poliüretan", sector: "Kimya" },
  { ticker: "DYOBY", name: "Dyo Boya", sector: "Kimya" },
  { ticker: "POLHO", name: "Polisan Holding", sector: "Kimya" },
  { ticker: "SASA",  name: "Sasa Polyester", sector: "Kimya" },
  { ticker: "KORDS", name: "Kordsa Teknik Tekstil", sector: "Kimya" },

  // İmalat, Kağıt & Kırtasiye
  { ticker: "GIPTA", name: "Gıpta Ofis Kırtasiye", sector: "İmalat / Kırtasiye" },
  { ticker: "LILAK", name: "Lila Kağıt", sector: "Kağıt & Ambalaj" },
  { ticker: "KARTN", name: "Kartonsan", sector: "Kağıt & Ambalaj" },
  { ticker: "ALKA",  name: "Alkim Kağıt", sector: "Kağıt & Ambalaj" },
  { ticker: "DURDO", name: "Duran Doğan Basım", sector: "Kağıt & Ambalaj" },
  { ticker: "KONKA", name: "Konya Kağıt", sector: "Kağıt & Ambalaj" },
  { ticker: "BAKAB", name: "Bak Ambalaj", sector: "Kağıt & Ambalaj" },
  { ticker: "BARMA", name: "Barem Ambalaj", sector: "Kağıt & Ambalaj" },
  { ticker: "TEZOL", name: "Europap Tezol Kağıt", sector: "Kağıt & Ambalaj" },

  // Gayrimenkul Yatırım Ortaklıkları (GYO)
  { ticker: "EKGYO", name: "Emlak Konut GYO", sector: "Gayrimenkul" },
  { ticker: "TORUN", name: "Torunlar GYO", sector: "Gayrimenkul" },
  { ticker: "ISGYO", name: "İş GYO", sector: "Gayrimenkul" },
  { ticker: "AKFGY", name: "Akfen GYO", sector: "Gayrimenkul" },
  { ticker: "SURGY", name: "Sur Tatil Evleri GYO", sector: "Gayrimenkul" },
  { ticker: "ADGYO", name: "Adra GYO", sector: "Gayrimenkul" },
  { ticker: "ASGYO", name: "Asce GYO", sector: "Gayrimenkul" },
  { ticker: "AVPGY", name: "Avrupakent GYO", sector: "Gayrimenkul" },
  { ticker: "BEGYO", name: "Batı Ege GYO", sector: "Gayrimenkul" },
  { ticker: "DZGYO", name: "Deniz GYO", sector: "Gayrimenkul" },
  { ticker: "HLGYO", name: "Halk GYO", sector: "Gayrimenkul" },
  { ticker: "KLGYO", name: "Kiler GYO", sector: "Gayrimenkul" },
  { ticker: "KZBGY", name: "Kızılbük GYO", sector: "Gayrimenkul" },
  { ticker: "OZKGY", name: "Özak GYO", sector: "Gayrimenkul" },
  { ticker: "PSGYO", name: "Pasifik GYO", sector: "Gayrimenkul" },
  { ticker: "TRGYO", name: "Torunlar GYO", sector: "Gayrimenkul" },
  { ticker: "VKGYO", name: "Vakıf GYO", sector: "Gayrimenkul" },
  { ticker: "ZRGYO", name: "Ziraat GYO", sector: "Gayrimenkul" },

  // Çimento, Yapı & Madencilik
  { ticker: "OYAKC", name: "Oyak Çimento", sector: "Çimento & Yapı" },
  { ticker: "CIMSA", name: "Çimsa Çimento", sector: "Çimento & Yapı" },
  { ticker: "AKCNS", name: "Akçansa Çimento", sector: "Çimento & Yapı" },
  { ticker: "NUHCM", name: "Nuh Çimento", sector: "Çimento & Yapı" },
  { ticker: "BOBET", name: "Boğaziçi Beton", sector: "Çimento & Yapı" },
  { ticker: "BUCIM", name: "Bursa Çimento", sector: "Çimento & Yapı" },
  { ticker: "BTCIM", name: "Batıçim Çimento", sector: "Çimento & Yapı" },
  { ticker: "BSOKE", name: "Batısöke Çimento", sector: "Çimento & Yapı" },
  { ticker: "LMKDC", name: "Limak Doğu Anadolu Çimento", sector: "Çimento & Yapı" },
  { ticker: "KOZAL", name: "Koza Altın İşletmeleri", sector: "Madencilik" },
  { ticker: "KOZAA", name: "Koza Anadolu Metal", sector: "Madencilik" },
  { ticker: "IPEKE", name: "İpek Doğal Enerji", sector: "Madencilik" },
  { ticker: "CVKMD", name: "CVK Madencilik", sector: "Madencilik" },

  // Dayanıklı Tüketim & Beyaz Eşya
  { ticker: "ARCLK", name: "Arçelik", sector: "Dayanıklı Tüketim" },
  { ticker: "VESBE", name: "Vestel Beyaz Eşya", sector: "Dayanıklı Tüketim" },
  { ticker: "VESTL", name: "Vestel Elektronik", sector: "Dayanıklı Tüketim" },
  { ticker: "ARZUM", name: "Arzum Elektrikli Ev Aletleri", sector: "Dayanıklı Tüketim" },
  { ticker: "SILVR", name: "Silverline Endüstri", sector: "Dayanıklı Tüketim" },

  // Sağlık & İlaç
  { ticker: "DEVA",  name: "Deva Holding", sector: "Sağlık & İlaç" },
  { ticker: "GENIL", name: "Gen İlaç", sector: "Sağlık & İlaç" },
  { ticker: "SELEC", name: "Selçuk Ecza Deposu", sector: "Sağlık & İlaç" },
  { ticker: "ECILC", name: "Eczacıbaşı İlaç", sector: "Sağlık & İlaç" },
  { ticker: "ECZYT", name: "Eczacıbaşı Yatırım", sector: "Sağlık & İlaç" },
  { ticker: "MPARK", name: "MLP Sağlık (Medical Park)", sector: "Sağlık" },
  { ticker: "MEDTR", name: "Meditera Tıbbi Malzeme", sector: "Sağlık" },
  { ticker: "TNZTP", name: "Tapdi Oksijen (Tınaztepe)", sector: "Sağlık" },

  // Sigorta & Finansal Hizmetler
  { ticker: "TURSG", name: "Türkiye Sigorta", sector: "Sigortacılık" },
  { ticker: "ANSGR", name: "Anadolu Sigorta", sector: "Sigortacılık" },
  { ticker: "AGESA", name: "Agesa Hayat ve Emeklilik", sector: "Sigortacılık" },
  { ticker: "ANHYT", name: "Anadolu Hayat Emeklilik", sector: "Sigortacılık" },
  { ticker: "AKGRT", name: "Aksigorta", sector: "Sigortacılık" },
  { ticker: "RAYSG", name: "Ray Sigorta", sector: "Sigortacılık" },
  { ticker: "ISMEN", name: "İş Yatırım Menkul Değerler", sector: "Finansal Hizmetler" },
  { ticker: "GEDIK", name: "Gedik Yatırım", sector: "Finansal Hizmetler" },
  { ticker: "INFO",  name: "İnfo Yatırım", sector: "Finansal Hizmetler" },
  { ticker: "OSMEN", name: "Osmanlı Yatırım", sector: "Finansal Hizmetler" },
  { ticker: "TERA",  name: "Tera Yatırım Menkul Değerler", sector: "Finansal Hizmetler" },
  { ticker: "UNLU",  name: "Ünlü & Co Yatırım", sector: "Finansal Hizmetler" },
];
